name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  config:  # id of input
    description: 'json configuration'
    required: true
    default: "[]"
runs:
  using: 'node12'
  main: 'index.js'
